CREATE TABLE COURSE (
    COURSE_NR                   INT NOT NULL CONSTRAINT COURSE_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME                        VARCHAR(15),
    DESCRIPTION                 VARCHAR(20),
    DURATION_OF_APPOINTMENT     INT,
    AMOUNT_OF_APPOINTMENTS      INT
);

CREATE TABLE INSTRUCTOR (
    INSTRUCTOR_NR               INT NOT NULL CONSTRAINT INSTRUCTOR_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME                  VARCHAR(15),
    LAST_NAME                   VARCHAR(25),
    PHONE_NR                    VARCHAR(15),
    EMAIL                       VARCHAR(20)
);

CREATE TABLE APPOINTMENT (
    APPOINTMENT_NR              INT NOT NULL CONSTRAINT APPOINTMENT_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    START                       DATE,
    INSTRUCTOR_NR               INT CONSTRAINT APP_FK REFERENCES INSTRUCTOR(INSTRUCTOR_NR)
);

CREATE TABLE PARTICIPANT (
     PARTICIPANT_NR             INT NOT NULL CONSTRAINT PARTICIPANT_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
     FIRST_NAME                 VARCHAR(15),
     YEAR_OF_BIRTH              INT,
     LAST_NAME                  VARCHAR(25),
     PHONE_NR                   VARCHAR(15),
     EMAIL                      VARCHAR(20)
);

CREATE TABLE REGISTRATION (
    PARTICIPANT_NR              INT NOT NULL,
    APPOINTMENT_NR              INT NOT NULL,
    CONSTRAINT PAR_APP_PK PRIMARY KEY (PARTICIPANT_NR, APPOINTMENT_NR),
    CONSTRAINT REG_PAR_FK FOREIGN KEY (PARTICIPANT_NR) REFERENCES PARTICIPANT(PARTICIPANT_NR),
    CONSTRAINT REG_APP_FK FOREIGN KEY (APPOINTMENT_NR) REFERENCES APPOINTMENT(APPOINTMENT_NR)
);


