CREATE TABLE CS_COURSE (
    C_ID                        INT NOT NULL CONSTRAINT C_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    C_NAME                      VARCHAR(50),
    C_DESCRIPTION               VARCHAR(150),
    C_MINUTES_PER_APPOINTMENT   INT,
    C_AMOUNT_OF_APPOINTMENTS    INT
);

CREATE TABLE CS_INSTRUCTOR (
    I_ID                        INT NOT NULL CONSTRAINT I_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    I_FIRST_NAME                VARCHAR(50),
    I_LAST_NAME                 VARCHAR(50),
    I_PHONE_NR                  VARCHAR(20),
    I_EMAIL                     VARCHAR(75)
);

CREATE TABLE CS_APPOINTMENT (
    A_ID                        INT NOT NULL CONSTRAINT A_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    A_START                     TIMESTAMP,
    A_I_ID                      INT CONSTRAINT A_I_FK REFERENCES CS_INSTRUCTOR(I_ID),
    A_C_ID                      INT CONSTRAINT A_C_FK REFERENCES CS_COURSE(C_ID)
);

CREATE TABLE CS_PARTICIPANT (
     P_ID                       INT NOT NULL CONSTRAINT P_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
     P_FIRST_NAME               VARCHAR(50),
     P_LAST_NAME                VARCHAR(50),
     P_YEAR_OF_BIRTH            INT,
     P_PHONE_NR                 VARCHAR(20),
     P_EMAIL                    VARCHAR(75)
);

CREATE TABLE CS_REGISTRATION (
    R_ID                        INT NOT NULL CONSTRAINT R_PK PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    R_P_ID                      INT NOT NULL,
    R_A_ID                      INT NOT NULL,
    CONSTRAINT R_P_FK FOREIGN KEY (R_P_ID) REFERENCES CS_PARTICIPANT(P_ID),
    CONSTRAINT R_A_FK FOREIGN KEY (R_A_ID) REFERENCES CS_APPOINTMENT(A_ID)
);


