------------------
--    Course    --
------------------
-- id = 1
INSERT INTO COURSE (NAME, DESCRIPTION, DURATION_OF_APPOINTMENT, AMOUNT_OF_APPOINTMENTS)
    VALUES ('Kinderschwimmen', 'Schwimmkurs fuer junge Personen', 1.0, 7);

-- id = 2
INSERT INTO COURSE (NAME, DESCRIPTION, DURATION_OF_APPOINTMENT, AMOUNT_OF_APPOINTMENTS)
    VALUES ('Seniorenschwimmen', 'Schwimmkurs fuer die aelteren unter uns', 2.0, 1);

-- id = 3
INSERT INTO COURSE (NAME, DESCRIPTION, DURATION_OF_APPOINTMENT, AMOUNT_OF_APPOINTMENTS)
    VALUES ('Einsteigerschwimmen', 'Schwimmkurs fuer Erwachsene', 1.5, 2);

-- id = 4
INSERT INTO COURSE (NAME, DESCRIPTION, DURATION_OF_APPOINTMENT, AMOUNT_OF_APPOINTMENTS)
    VALUES ('Babyschwimmen', 'Schwimmkurs fuer Neugeborene', 0.5, 4);


----------------------
--    INSTRUCTOR    --
----------------------
-- id = 1
INSERT INTO INSTRUCTOR (FIRST_NAME, LAST_NAME, PHONE_NR, EMAIL)
    VALUES ('Hans', 'Hofer', '+43 681 2274803', 'h.hofer@yahoomail.com');

-- id = 2
INSERT INTO INSTRUCTOR (FIRST_NAME, LAST_NAME, PHONE_NR, EMAIL)
    VALUES ('Iris', 'Mayr', '+43 699 21228202', 'iri.myr@fastmail.to');

-- id = 3
INSERT INTO INSTRUCTOR (FIRST_NAME, LAST_NAME, PHONE_NR, EMAIL)
    VALUES ('Franz', 'Leitner', '+43 660 093298743', 'leitner.f@gmail.com');

-- id = 4
INSERT INTO INSTRUCTOR (FIRST_NAME, LAST_NAME, PHONE_NR, EMAIL)
    VALUES ('Susanne', 'Obermaier', '+43 680 009796552', 'susi.obermaier@hotmail.net');

-- id = 5
INSERT INTO INSTRUCTOR (FIRST_NAME, LAST_NAME, PHONE_NR, EMAIL)
    VALUES ('Markus', 'Kittinger', '+43 677 66333221', 'k.markus@gmx.at');

-- id = 6
INSERT INTO INSTRUCTOR (FIRST_NAME, LAST_NAME, PHONE_NR, EMAIL)
    VALUES ('Hermine', 'Stieglbauer', '+43 665 7676323', 'stiegelbauer.h@liwest.at');

-- id = 7
INSERT INTO INSTRUCTOR (FIRST_NAME, LAST_NAME, PHONE_NR, EMAIL)
    VALUES ('Kurt', 'Wolfsgruber', '+43 670 98764332', 'kurt.wolfsgruber@icloud.com');

-- id = 8
INSERT INTO INSTRUCTOR (FIRST_NAME, LAST_NAME, PHONE_NR, EMAIL)
    VALUES ('Antonia', 'Grabmann', '+43 678 87654543', 'toni.grabmann@freemail.tk.to');

-- id = 9
INSERT INTO INSTRUCTOR (FIRST_NAME, LAST_NAME, PHONE_NR, EMAIL)
    VALUES ('Norbert', 'Kleeberger', '+43 650 20987634', 'kleeberger.norbert@zoho.com');

-- id = 10
INSERT INTO INSTRUCTOR (FIRST_NAME, LAST_NAME, PHONE_NR, EMAIL)
    VALUES ('Roswita', 'Neuhauser', '+43 660 84350982', 'neuhauser.roswi@protonmail.com');


-----------------------
--    APPOINTMENT    --
-----------------------
-- id = 1
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2022-12-14', 1, 1);

-- id = 2
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2022-12-21', 1, 1);

-- id = 3
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-01-11', 2, 1);

-- id = 4
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-01-18', 9, 1);

-- id = 5
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-01-25', 3, 1);

-- id = 6
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-02-01', 8, 1);

-- id = 7
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-01-01', 4, 1);

-- id = 8
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-02-22', 7, 2);

-- id = 9
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-04-07', 5, 3);

-- id = 10
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-04-14', 6, 3);

-- id = 11
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-05-09', 3, 4);

-- id = 12
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-05-16', 3, 4);

-- id = 13
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-05-23', 6, 4);

-- id = 14
INSERT INTO APPOINTMENT (START, INSTRUCTOR_NR, COURSE_NR)
    VALUES ('2023-05-30', 4, 4);


-----------------------
--    PARTICIPANT    --
-----------------------
-- id = 1
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Josef', 'Baumgartner', 2000, '+43 681 0387440179', 'j.baumgrt@gmail.com');

-- id = 2
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Gudrun', 'Weiss', 1997, '+43 699 34986601', 'weiss.g@gmx.at');

-- id = 3
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Joerg', 'Haider', 1972, '+43 686 234510972', 'j.haider@moderner-brief.de');

-- id = 4
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Leopoldine', 'Hofmeister', 1988, '+43 664 444234861', 'leopoldine.hofmeister@hotmail.net');

-- id = 5
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Leon', 'Hoefler', 2009, '+43 650 8987023411', 'leon.hoefler@icloud.com');

-- id = 6
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Dilan', 'Oezdemir', 2011, '+43 677 2332469031', 'd.oezdemir@gmail.com');

-- id = 7
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Lukas', 'Binder', 2012, '+43 690 23496551', 'lukas.binder@proton-mail.net');

-- id = 8
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Emma', 'Kaltenboeck', 2010, '+43 686 23585213', 'e.kaltenboeck@liwest.at');

-- id = 9
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Innozenz', 'Wild', 1948, '+43 678 3248877112', 'i.wild@morderner-brief.de');

-- id = 10
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Maria', 'Hinterbichler', 1947, '+43 677 32689874', 'm.hinterbichler@yahoomail.com');

-- id = 11
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Karl', 'Grossauer', 1949, '+43 681 098437256', 'grossauer.karl@gmail.com');

-- id = 12
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Andrea', 'Koenig', 1993, '+43 681 03874487324', 'a.koenig@gmx.at');

-- id = 13
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Martin', 'Egger', 1941, '+43 676 0972454358', 'martin.egger@neuland.de');

-- id = 14
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Lena', 'Reisinger', 2012, '+43 650 3287763432', 'lena.reisinger@gmail.com');

-- id = 15
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Anis', 'Zadic', 2010, '+43 664 23487743671', 'a.zadic@gmail.com');

-- id = 16
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Alexander', 'Kern', 2022, '+43 667 65732386', 'friedrich.kern@gmx.at');

-- id = 17
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Julia', 'Herr', 2021, '+43 676 293746801', 'kerstin.herr@liwest.at');

-- id = 18
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Leo', 'Kerbel', 2021, '+43 664 087432987', 'gregor.kerbel@yahoomail.com');

-- id = 19
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Elif', 'Demir', 2022, '+43 650 99877623012', 'o.demir@gmail.com');

-- id = 20
INSERT INTO PARTICIPANT (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, PHONE_NR, EMAIL)
    VALUES ('Maximilian', 'Steinmayr', 2002, '+43 699 8174628091', 'max.steinmayr@gmail.com');

------------------------
--    REGISTRATION    --
------------------------
-- id = 1
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (9, 8);

-- id = 2
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (10, 8);

-- id = 3
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (11, 8);

-- id = 4
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (13, 8);

-- id = 5
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (1, 9);

-- id = 6
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (1, 10);

-- id = 7
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (2, 9);

-- id = 8
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (2, 10);

-- id = 9
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (3, 9);

-- id = 10
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (3, 10);

-- id = 11
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (4, 9);

-- id = 12
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (12, 10);

-- id = 13
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (20, 9);

-- id = 14
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (16, 11);

-- id = 15
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (16, 12);

-- id = 16
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (16, 13);

-- id = 17
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (16, 14);

-- id = 18
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (17, 11);

-- id = 19
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (17, 12);

-- id = 20
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (17, 14);

-- id = 21
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (18, 12);

-- id = 22
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (18, 13);

-- id = 23
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (18, 14);

-- id = 24
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (19, 11);

-- id = 25
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (19, 14);

-- id = 26
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (5, 1);

-- id = 27
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (5, 2);

-- id = 28
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (5, 3);

-- id = 29
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (5, 4);

-- id = 30
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (5, 5);

-- id = 31
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (5, 6);

-- id = 32
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (5, 7);

-- id = 33
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (6, 2);

-- id = 34
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (6, 7);

-- id = 35
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (6, 6);

-- id = 36
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (6, 5);

-- id = 37
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (6, 4);

-- id = 38
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (6, 3);

-- id = 39
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (7, 3);

-- id = 40
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (7, 4);

-- id = 41
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (7, 5);

-- id = 42
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (7, 6);

-- id = 43
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (7, 7);

-- id = 44
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (8, 1);

-- id = 45
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (8, 2);

-- id = 46
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (8, 3);

-- id = 47
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (8, 4);

-- id = 48
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (14, 4);

-- id = 48
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (14, 5);

-- id = 49
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (14, 6);

-- id = 50
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (15, 7);

-- id = 51
INSERT INTO REGISTRATION (PARTICIPANT_NR, APPOINTMENT_NR)
    VALUES (15, 6);