@startuml
skinparam actorstyle awesome
left to right direction

actor "Teilnehmer" as tn
actor "Administrator" as adm

rectangle Kursterminverwaltung {
    usecase "Termine eines Kurses einsehen" as te
    usecase "Für einen Termin anmelden" as an
    usecase "Von einem Termin abmelden" as ab
    usecase "Kurse verwalten" as kv
    usecase "Termine verwalten" as tv
    usecase "Teilnehmer verwalten" as tw

    tn -- te
    tn -- an
    tn -- ab
    adm -- kv
    adm -- tw
    adm -- tv
}


@enduml

